# Generated by Django 3.1.7 on 2021-03-16 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tempo',
            new_name='Weather',
        ),
    ]
