# Generated by Django 3.1.7 on 2021-03-16 21:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20210316_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='hora',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
