# Generated by Django 3.1.7 on 2021-03-16 21:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_weather_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='hora',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
